import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f0f4f8" },
  content: { padding: 16, gap: 16 },
  statCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 3,
  },
  statTitle: { fontSize: 13, color: "#888", marginBottom: 4 },
  statValue: { fontSize: 22, fontWeight: "700", color: "#1a1a2e" },
  progressTrack: {
    height: 8,
    backgroundColor: "#e5e7eb",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: {
    height: 8,
    backgroundColor: "#1e40af",
    borderRadius: 4,
  },
  progressLabel: { fontSize: 12, color: "#888", marginTop: 4 },
  maintenanceMessage: { fontSize: 13, marginTop: 8 },
  fixBtn: {
    marginTop: 12,
    backgroundColor: "#6b7280",
    borderRadius: 8,
    padding: 10,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  fixBtnCritical: { backgroundColor: "#ef4444" },
  fixBtnText: { color: "#fff", fontWeight: "600" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalBox: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 24,
    width: "80%",
  },
  modalTitle: { fontSize: 18, fontWeight: "700", marginBottom: 8 },
  modalMessage: { fontSize: 14, color: "#555", marginBottom: 20 },
  modalButtons: { flexDirection: "row", justifyContent: "flex-end", gap: 12 },
  cancelBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#e5e7eb",
  },
  cancelBtnText: { color: "#333", fontWeight: "600" },
  confirmBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#1e40af",
  },
  confirmBtnText: { color: "#fff", fontWeight: "600" },
});